[telegram]
name = "dmmsearchbot"
api_id = 12581928
api_hash = "9bd003806267466f904f91aa035d8991"
bot_token = "5825162076:AAGVlR9eRx9uYHh3FwCPH3CKcsSl-dOGCPA"

[DMM]
api_id = "bYga4ba5HUvnZzsvH30U"
affiliate_id = "dmmidofbot-990"
